name: Native Mode Tests

on:
  push:
    tags: [ v* ]
  workflow_dispatch:

jobs:
  test-core-native:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        maven_profiles: ["jackson", "resteasy-jackson", "jsonb", "resteasy-jsonb"]

    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
          cache: 'maven'

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile
        run: ./mvnw install -Pquick

      - name: Native Tests
        run: ./mvnw -f integration-test/pom.xml clean verify -P it,native,${{ matrix.maven_profiles }}